### ISSUE TITLE
Why do we restrict to 320x320?

### ISSUE THREAD

**Issue by chaithyagr** [zaccharieramzi/tf-fastmri-data#33]
https://github.com/zaccharieramzi/tf-fastmri-data/blob/17592b3d9f74d2940c5ef8cbb3f5351f7ba92b3a/tf_fastmri_data/dataset_builder.py#L146-L150

In above code, I feel its best to just not hardcode and rather just crop the data by later pipelines and not initially itself as this makes the data shapes as None, None etc. Also, using adjust_image_size is surely a better alternative (however, I dont want to crop here at all)

**Comment by chaithyagr** [comment]
@zaccharieramzi opinions?

**Comment by zaccharieramzi** [comment]
I think you are right, cropping should be left for future steps
